# Generated by Django 3.0.5 on 2025-10-25 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='assigned_doctorId',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='symptoms',
        ),
    ]
