# Generated by Django 3.0.5 on 2025-11-03 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_patient_assigned_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='assigned_doctorName',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='patientId',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='patientName',
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Doctor'),
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.Patient'),
        ),
    ]
