# Generated by Django 3.0.5 on 2025-11-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_auto_20251103_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalreport',
            options={'ordering': ['-uploaded_date']},
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='file',
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_fee',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualifications',
            field=models.CharField(default='MBBS', max_length=200),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='report_file',
            field=models.FileField(default='', upload_to='medical_reports/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='title',
            field=models.CharField(default='Medical Report', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='description',
            field=models.TextField(),
        ),
    ]
